### ISSUE TITLE
Use TCK for testing

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa-opencypher-xtext#26]
As #24 demonstrated, it is very easy to introduce errors. Therefore, I'd propose to use the [openCypher TCK](https://github.com/opencypher/openCypher/tree/master/tck) (or a subset of it) to test the parser.

**Comment by wuetherich** [comment]
I also had a similar idea when I saw that the OpenCypher project also provides a TCK. The problem is that the tests in the TCK are not (just) parser tests. They also expect and test a specific behaviour from an implementing backend/graph database. Simple example:

`  Scenario: Creating two nodes
    Given any graph
    When executing query:
      """
      CREATE (), ()
      """
    Then the result should be empty
    And the side effects should be:
      | +nodes | 2 |`

This test executes a statement and expects an empty result and a change in an underlying database. As opencypher-xtext only provides a parser, it doesn't make sense the use the TCK as it is.

On the other hand the TCK contains a bunch of cypher queries, and I'm pretty sure that it contains many types of queries that are not covered in the opencypher-xtext test suite.

From my pov it would be the easiest solution to implement a test helper utility that parses the TCK *.feature files and extract all cypher queries, so that they can be executed within the existing test framework. What do you think?

**Comment by szarnyasg** [comment]
Yes, this was exactly what I was thinking. Fortunately, I had an old Python script lying around in the [ingraph project](https://github.com/FTSRG/ingraph/blob/b37a871ec5ffcf7f85e4984b3d46c64f40432150/opencypher-tests/generate-parser-tests.py), so I tinkered with it a bit and the result is in PR #28 (not ready to merge).

Note that although this is very comprehensive, it does not provide total coverage of the grammar, as the TCK does not consider legacy language features (regexes, foreach, shortestPath, etc.).

**Comment by wuetherich** [comment]
ah, cool, looks great ;-)
